"""change platform column to platforms.

Revision ID: 6528f7192328
Revises: 9d75fc7f00bd
Create Date: 2023-04-29 16:17:53.416078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6528f7192328'
down_revision = '9d75fc7f00bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platforms', sa.String(), nullable=False))
        batch_op.drop_column('platform')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('platforms')

    # ### end Alembic commands ###
